#
# Cost map common parameters
#
map_type:       costmap

obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.35 # 0.25 for udacity_bot
inflation_radius: 0.5

transform_tolerance: 0.2

odom_model_type: "diff-corrected"   # (string, default "diff") Which model to use, either "diff", "omni", "diff-corrected" or "omni-corrected".

observation_sources: laser_scan_sensor
laser_scan_sensor:   {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}




